### ISSUE TITLE
Level 1 (MVP)

### ISSUE THREAD

**Issue by olikelly00** [SchoolOfCode/escape-room-hackathon-rnine#1]
[ ] Create start button
[ ] Create initial room scene
[ ] Create door sprite
[ ] Create player sprite
[ ] Implement player movement within the room
[ ] Design and add puzzle clues to the room
[ ] Implement puzzle solution checking mechanism in Scratch code
[ ] Create red X sprite
[ ] Add red X sprite to UI for incorrect puzzle attempts
[ ] Implement transition from initial room to garden upon puzzle completion

**Comment by 4rchie-r** [comment]
Successfully completed these tasks.
