### ISSUE TITLE
Level 2

### ISSUE THREAD

**Issue by olikelly00** [SchoolOfCode/escape-room-hackathon-rnine#2]
[ ] Create house / garden path background and add to UI
[ ] Create interactive bushes in the garden
[ ] Implement key hiding mechanism under bushes
[ ] Add player interaction to search under bushes
[ ] Create door sprite
[ ] Implement door interaction (locked/unlocked states)
[ ] Add win condition when player unlocks door with key

**Comment by 4rchie-r** [comment]
All is fixed!
